services:
  app:
    build:
      context: .
      args:
        - enable_mecab=1
    platform: linux/amd64
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - './config.json:/subaru/config.json:ro'
      - './font.ttf:/subaru/font.ttf:ro'
      - './data:/subaru/data'
    restart: always
